import { Video } from "src/types";

export const videoData: Video[] = [
	{
		id: 1,
		title: "video_1",
		src: "/videos/1.mp4",
		description: "An AI‑generated beach scene at sunrise.",
		hashtags: "#ai #beach #sunrise",
		likes_count: 1200,
		comments_count: 345,
		share_count: 78,
	},
	{
		id: 2,
		title: "video_2",
		src: "/videos/2.mp4",
		description: "A futuristic cityscape rendered by AI.",
		hashtags: "#ai #cityscape #futuristic",
		likes_count: 980,
		comments_count: 210,
		share_count: 64,
	},
	{
		id: 3,
		title: "video_3",
		src: "/videos/3.mp4",
		description: "AI-created mountain panorama in autumn.",
		hashtags: "#ai #mountains #autumn",
		likes_count: 1575,
		comments_count: 412,
		share_count: 89,
	},
	{
		id: 4,
		title: "video_4",
		src: "/videos/4.mp4",
		description: "A serene forest path generated by AI.",
		hashtags: "#ai #forest #nature",
		likes_count: 860,
		comments_count: 134,
		share_count: 47,
	},
];
